### ISSUE TITLE
does not seem to be claiming disk space on epiphany 3.22 / webkitgtk 2.14

### ISSUE THREAD

**Issue by kapouer** [feross/filldisk.com#12]
And that can be tested on a recent Fedora or Debian version.
I checked several places and cannot find anything growing:
- .local/share/epiphany
- .local/share/webkitgtk
- .cache/epiphany
- .cache/webkitgtk

and also `df -h` does not change.

**Comment by feross** [comment]
I've never heard of Epiphany browser. It's great that it's not vulnerable to this issue, though! Closing as there's nothing I intend to do about this.

**Comment by kapouer** [comment]
It's the "gnome" web browser, which uses a port of webkit to gtk, available on Fedora, Debian, Ubuntu.
(FYI).
